version: "3"

services:
   mysql:
     image: mysql:5.6
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: demo
       MYSQL_USER: demo_user
       MYSQL_PASSWORD: demo_pass

   spasboot:
     depends_on:
       - mysql
     image: rajeshgheware/spa-sboot-docker:1.3.0
     ports:
       - "8080:8080"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: demo_user
       WORDPRESS_DB_PASSWORD: demo_pass
volumes:
    db_data: